//this will be your layout page -- it may not need modification

import './globals.css'
import { Inter } from 'next/font/google'
import { UserContextProvider } from './userContext';
import NavBar from './components/NavBar'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Waggle',
  description: 'Generated by create next app',
  type: 'website',
  siteName: 'waggle',
  locale: 'en_US'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
        <head>
          <link rel="icon" type="image/png" href="/logo.png" />
        </head>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </UserContextProvider>
    </html>
  )
}
